### ISSUE TITLE
login with facebook crash with API31

### ISSUE THREAD

**Issue by pmainville-clgx** [LoginRadius/android-sdk#5]
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5368)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by indrasen715** [comment]
Hi @pmainville-clgx 
Thanks for bringing this to our notice and we appreciate your valuable feedback on this.

I will review this feedback with the team, and keep you posted on the progress.

Regards

**Comment by indrasen715** [comment]
HI @pmainville-clgx 

Thanks for your contribution to this project, this issue is fixed in our latest [Release Version 5.0.0 ](https://github.com/LoginRadius/android-sdk/releases/tag/5.0.0.)
Please let me know if you see any other areas of improvement. 

Regards
Indrasen
